SkillsFundingAgency/das-apply-service

src/SFA.DAS.ApplyService.Application/Email/Consts/EmailTemplateName.cs
src/SFA.DAS.ApplyService.Application/Users/CreateAccount/CreateAccountHandler.cs
src/SFA.DAS.ApplyService.Database/Script.PostDeployment1.sql

This adds the coirrect Signup Error Email Teamplate

Add ApplySignupError Email template

---

src/WorkflowLatest.sql

Also changed only one of the FHA uploads to be required and set both of them as PDF only.

Updated workflow json to stop Registered charity page disappearing

---

src/SFA.DAS.ApplyService.Data/ApplyRepository.cs

Closed applications to filter solely on sequence status

ON-1434 - Manage Closed Applications #2

---

src/SFA.DAS.ApplyService.Data/ApplyRepository.cs

There was an redundant inner join (hidden by the group by clause)

ON-1434 - Optimise GetClosedApplications query

---

src/SFA.DAS.ApplyService.Application.UnitTests/Handlers/ApplicationSubmitHandlerTests/ApplicationSubmitHandlerTestsBase.cs
src/SFA.DAS.ApplyService.Application.UnitTests/Handlers/ApplicationSubmitHandlerTests/When_submitting_sequence_1.cs
src/SFA.DAS.ApplyService.Application.UnitTests/Handlers/ApplicationSubmitHandlerTests/When_submitting_sequence_2.cs
src/SFA.DAS.ApplyService.Application.UnitTests/MoqExtensions.cs
src/SFA.DAS.ApplyService.Application/Apply/UpdateApplicationData/UpdateApplicationDataHandler.cs

Didn't get far with this, however managed to add tests for ApplicationSubmitHandler and fix a bug in UpdateApplicationDataHandler

Improve test coverage

---

.gitignore

Updated gitignore with *.developer.json so that individual devs can have different settings and they not get overwritten

Updated gitignore 

---

src/SFA.DAS.ApplyService.Web/Views/Application/Pages/Controls/_Date.cshtml
src/SFA.DAS.ApplyService.Web/Views/Application/Pages/MultipleAnswers.cshtml
src/SFA.DAS.ApplyService.Web/Views/Application/Standard/FindStandard.cshtml
src/SFA.DAS.ApplyService.Web/Views/Users/CreateAccount.cshtml

Reverts SkillsFundingAgency/das-apply-service#143

Revert "On 1773 multiple answer questions"

---

src/SFA.DAS.ApplyService.Application.UnitTests/Handlers/UpdatePageAnswersHandlerTests/UpdatePageAnswersHandlerTestBase.cs
src/SFA.DAS.ApplyService.Application.UnitTests/Handlers/UpdatePageAnswersHandlerTests/When_all_requested_feedback_is_completed.cs
src/SFA.DAS.ApplyService.Application.UnitTests/Handlers/UpdatePageAnswersHandlerTests/When_all_requested_feedback_is_not_completed.cs
src/SFA.DAS.ApplyService.Application.UnitTests/Handlers/UpdatePageAnswersHandlerTests/When_answer_with_further_answer_is_provided.cs
src/SFA.DAS.ApplyService.Application.UnitTests/Handlers/UpdatePageAnswersHandlerTests/When_answer_with_further_answer_missing_is_provided.cs
src/SFA.DAS.ApplyService.Application.UnitTests/Handlers/UpdatePageAnswersHandlerTests/When_first_answers_on_multiple_answers_page_are_provided.cs
src/SFA.DAS.ApplyService.Application.UnitTests/Handlers/UpdatePageAnswersHandlerTests/When_no_answers_on_multiple_answers_page_with_existing_answers_are_provided.cs
src/SFA.DAS.ApplyService.Application.UnitTests/Handlers/UpdatePageAnswersHandlerTests/When_no_answers_on_multiple_answers_page_without_existing_answers_are_provided.cs
src/SFA.DAS.ApplyService.Application.UnitTests/Handlers/UpdatePageAnswersHandlerTests/When_partial_answers_on_multiple_answers_page_with_existing_answers_are_provided.cs
src/SFA.DAS.ApplyService.Application.UnitTests/Handlers/UpdatePageAnswersHandlerTests/When_valid_answer_for_conditional_question_is_provided.cs
src/SFA.DAS.ApplyService.Application.UnitTests/Handlers/UpdatePageAnswersHandlerTests/When_valid_answers_are_provided.cs
src/SFA.DAS.ApplyService.Application.UnitTests/Handlers/UpdatePageAnswersHandlerTests/When_valid_answers_on_multiple_answers_page_with_existing_answers_are_provided.cs
src/SFA.DAS.ApplyService.Application/Apply/DeleteAnswer/DeletePageAnswerHandler.cs
src/SFA.DAS.ApplyService.Application/Apply/UpdatePageAnswers/UpdatePageAnswersHandler.cs
src/SFA.DAS.ApplyService.Application/Apply/UpdatePageAnswers/UpdatePageAnswersRequest.cs
src/SFA.DAS.ApplyService.InternalApi.Types/PageApplyRequest.cs
src/SFA.DAS.ApplyService.InternalApi/Controllers/ApplicationController.cs
src/SFA.DAS.ApplyService.Web/Controllers/ApplicationController.cs
src/SFA.DAS.ApplyService.Web/Infrastructure/ApplicationApiClient.cs
src/SFA.DAS.ApplyService.Web/Infrastructure/IApplicationApiClient.cs
src/SFA.DAS.ApplyService.Web/Views/Application/Pages/Controls/_Date.cshtml
src/SFA.DAS.ApplyService.Web/Views/Application/Pages/Index.cshtml
src/SFA.DAS.ApplyService.Web/Views/Application/Pages/MultipleAnswers.cshtml

Save and continue is now possible for multiple answer pages e.g. Directors.

On 1763 multiple answer questions save and continue

---

src/SFA.DAS.ApplyService.Application/Users/IContactRepository.cs
src/SFA.DAS.ApplyService.Application/Users/RemoveContact/RemoveContactFromOrganisationRequest.cs
src/SFA.DAS.ApplyService.Data/ContactRepository.cs
src/SFA.DAS.ApplyService.InternalApi/Controllers/AccountController.cs

This is a small change to Apply so that when a user is removed from an org in Assessor, they are also removed in Apply.

ON-1862 Added endpoint and handler for removing a contact from an organisation

---

src/SFA.DAS.ApplyService.Application/Users/CreateNewContact/CreateNewContactHandler.cs
src/SFA.DAS.ApplyService.Application/Users/CreateNewContact/CreateNewContactRequest.cs
src/SFA.DAS.ApplyService.Application/Users/UpdateContactOrgId/UpdateContactOrganisationIdHandler.cs
src/SFA.DAS.ApplyService.Application/Users/UpdateContactOrgId/UpdateContactOrganisationIdRequest.cs
src/SFA.DAS.ApplyService.Application/Users/UpdateSignInId/UpdateSignInRequestHandler.cs
src/SFA.DAS.ApplyService.Data/ContactRepository.cs
src/SFA.DAS.ApplyService.InternalApi.Types/SFA.DAS.ApplyService.InternalApi.Types.csproj
src/SFA.DAS.ApplyService.InternalApi.Types/SignInCallback.cs
src/SFA.DAS.ApplyService.InternalApi/Controllers/AccountController.cs
src/SFA.DAS.ApplyService.InternalApi/Validators/Account/DfeSignInCallbackValidator.cs
src/SFA.DAS.ApplyService.Web/Controllers/AccountController.cs
src/SFA.DAS.ApplyService.Web/Infrastructure/UsersApiClient.cs

Support for Assessor's Invite User to the Organisation work.

On 1859 invite user to organisation

---

src/SFA.DAS.ApplyService.Domain/CompaniesHouse/CompaniesHouseSummary.cs
src/SFA.DAS.ApplyService.Web.UnitTests/Controllers/RoatpApplicationPreambleControllerTests.cs
src/SFA.DAS.ApplyService.Web.UnitTests/IncorporationDateValidatorTests.cs
src/SFA.DAS.ApplyService.Web/AutoMapper/CompaniesHouseProfile.cs
src/SFA.DAS.ApplyService.Web/Controllers/Roatp/RoatpApplicationPreambleController.cs
src/SFA.DAS.ApplyService.Web/Validators/IncorporationDateValidator.cs
src/SFA.DAS.ApplyService.Web/Views/Roatp/InvalidCompanyTradingHistory.cshtml

Add flag to indicate that additional information required as the Companies House API call will not return directors/PSCs for certain company number prefixes

APR-506 add flag to indicate that additional information required

---

src/SFA.DAS.ApplyService.Web/Controllers/ApplicationController.cs

As discussed with Deen the second scenario in this story also takes you to the list of application screen, and from there a new application can be started and then the current follow will take care of financials.

 ON-2068 Allow Existing EPAO to apply for multiple standards

---

src/SFA.DAS.ApplyService.InternalApi/web.config
src/SFA.DAS.ApplyService.Web/web.config

Testing combinations of version of .netcore and AspNetCoreModule

ON-1905 Revert AspNetCoreModuleV2 to AspNetCoreModule

---

src/SFA.DAS.ApplyService.InternalApi/Program.cs

make order the same in both APP and API

Re-order startup and add explicit Kestrel

---

src/SFA.DAS.ApplyService.Web/Views/Application/Submitted.cshtml

Show different 'what happens next' content depending on which stage user is at

ON-2196 / ON-2171 - 'what happens next' content

---

src/SFA.DAS.ApplyService.Domain/Apply/Input.cs
src/SFA.DAS.ApplyService.Web/SFA.DAS.ApplyService.Web.csproj

APR-1144 collecting apprenticeship data

---

azure/template.json

Removed swap slot health check ping as no longer needed with the slot health check script

Removed swap slot health check ping

---

src/SFA.DAS.ApplyService.Web/Controllers/Roatp/RoatpApplicationController.cs

This code was eventually copied from EPAO & Config Preview

Store entered answers when the page is invalid

---

src/SFA.DAS.ApplyService.Database/Script.PostDeployment1.sql

use '7e7a46e1-d203-486a-ac1b-40e8a617ef0d' for 'f371098e-4e91-40ae-96da-d6f8d9c85251'
use '68008288-6497-4de2-be3c-e1409538aad9' for 'c0008332-7a20-41a4-94d4-57acbcebaef8'

For Private Beta

---

.github/CODEOWNERS
.gitignore
README.md
sonarcloud/Dockerfile
sonarcloud/analyse.ps1

Adds Dockerfile to run SonarCloud analysis locally

:whale: Adds SonarCloud Dockerfile

---

src/SFA.DAS.ApplyService.Database/Tables/AssessorPageReviewOutcome.sql
src/SFA.DAS.ApplyService.Database/Tables/ModeratorPageReviewOutcome.sql
src/SFA.DAS.ApplyService.InternalApi.Types/Assessor/AssessorSection.cs
src/SFA.DAS.ApplyService.InternalApi.UnitTests/Services/Assessor/AssessorReviewCreationServiceTests.cs
src/SFA.DAS.ApplyService.InternalApi.UnitTests/Services/Assessor/AssessorSectorServiceTests.cs
src/SFA.DAS.ApplyService.InternalApi.UnitTests/Services/Moderator/ModeratorReviewCreationServiceTests.cs
src/SFA.DAS.ApplyService.InternalApi/Services/Assessor/AssessorReviewCreationService.cs
src/SFA.DAS.ApplyService.InternalApi/Services/Assessor/AssessorSectorService.cs
src/SFA.DAS.ApplyService.InternalApi/Services/Assessor/AssessorSequenceService.cs
src/SFA.DAS.ApplyService.InternalApi/Services/Assessor/IAssessorSectorService.cs
src/SFA.DAS.ApplyService.InternalApi/Services/Moderator/ModeratorReviewCreationService.cs

Previous solution made numerous calls to QNA API - this version can do it in 1 call

APR-1888 - Optimise Create Empty Review Process

---

src/SFA.DAS.ApplyService.Domain/Entities/InitialTeacherTraining.cs
src/SFA.DAS.ApplyService.InternalApi.UnitTests/ExperienceAndAccreditationControllerTests.cs
src/SFA.DAS.ApplyService.InternalApi/Controllers/ExperienceAndAccreditationController.cs

…hip when getting initial teacher training for gateway

APR-1912 - Updated Not Required logic for OFS & Ofsted sections

---

src/SFA.DAS.ApplyService.Application/Apply/Gateway/GetGatewayPageAnswerHandler.cs
src/SFA.DAS.ApplyService.Application/Apply/Gateway/GetGatewayPageAnswerRequest.cs
src/SFA.DAS.ApplyService.Application/Apply/Gateway/GetGatewayPagesHandler.cs
src/SFA.DAS.ApplyService.Application/Apply/Gateway/GetGatewayPagesRequest.cs
src/SFA.DAS.ApplyService.Application/Apply/IApplyRepository.cs
src/SFA.DAS.ApplyService.Data/ApplyRepository.cs
src/SFA.DAS.ApplyService.Domain/Entities/GatewayPageAnswer.cs
src/SFA.DAS.ApplyService.InternalApi.Types/GatewayCommonDetails.cs
src/SFA.DAS.ApplyService.InternalApi/Controllers/RoatpGatewayController.cs

Also includes some refactoring work

APR-2034 : Gateway readonly page

---

azure-pipelines.yml

Matches Nuget package publishing in https://github.com/SkillsFundingAgency/das-admin-service/blob/master/azure-pipelines.yml

DASD-8516: Added Nuget pack and publish of SFA.DAS.ApplyService.Types.csproj

---

src/SFA.DAS.ApplyService.Web/appsettings.json

ROATP : Financial evidence content changes

---

src/SFA.DAS.ApplyService.Web/Views/Roatp/ApplicationRejected.cshtml
src/SFA.DAS.ApplyService.Web/Views/Roatp/ApplicationUnsuccessfulPostGateway.cshtml
src/SFA.DAS.ApplyService.Web/Views/Roatp/ChangeUkprn.cshtml
src/SFA.DAS.ApplyService.Web/Views/Roatp/ConditionsOfAcceptance.cshtml
src/SFA.DAS.ApplyService.Web/Views/Roatp/ConfirmChangeRoute.cshtml
src/SFA.DAS.ApplyService.Web/Views/Roatp/ConfirmLevyStatus.cshtml
src/SFA.DAS.ApplyService.Web/Views/Roatp/ProviderAlreadyOnRegister.cshtml
src/SFA.DAS.ApplyService.Web/Views/Roatp/SelectApplicationRoute.cshtml
src/SFA.DAS.ApplyService.Web/Views/Roatp/_AppealComplaintContact.cshtml
src/SFA.DAS.ApplyService.Web/Views/Roatp/_ApplicationApprovedContactDetails.cshtml

- add CSS class to links
- add missing `<legend>` to `<fieldset>`s

Apr 2862 accessibility

---

src/SFA.DAS.ApplyService.Web/Views/Users/ChangeSignInDetails.cshtml

Content updated in Change of Details Page
FAI-872 & FAI-935
Story: https://skillsfundingagency.atlassian.net/browse/FAI-935

FAI-872 & FAI-935 Content updated in Change of Details Page

---

src/SFA.DAS.ApplyService.Web.UnitTests/Controllers/HomeControllerTests.cs
src/SFA.DAS.ApplyService.Web.UnitTests/Models/WhenBuildingHomeViewModel.cs
src/SFA.DAS.ApplyService.Web/ViewModels/HomeIndexViewModel.cs
src/SFA.DAS.ApplyService.Web/Views/Home/Index.cshtml

CTA button changes matching Copy doc
https://skillsfundingagency.atlassian.net/browse/FAI-796

FAI-872 FAI-796 CTA button changes matching Copy doc
